name: 'Build and save artifact'

on:
  push:
    branches: main

jobs:
  build_and_save_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '16'
      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6
          run_install: true
      - name: build
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist